Final_Wave/Areas/AdminArea/Controllers/ProductGalleryController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Final_Wave.Core.PulicClasses;
using Final_Wave.Core.ViewModels;
using Final_Wave.DataLayer.Entites;
using Final_Wave.DataLayer.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Final_Wave.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize]
    public class ProductGalleryController : Controller
    {

        private readonly IUnitOfWork _context;
        private readonly IMapper _mapper;
        private readonly INotyfService _notify;
        public ProductGalleryController(IUnitOfWork context, IMapper mapper, INotyfService notyf)
        {
            _context = context;
            _mapper = mapper;
            _notify = notyf;

        }
        public async Task<IActionResult> Index(int id)
        {
            var product = await _context.productUW.GetEntitiesAsync();
            ViewBag.ProductId = id;
            var mapModel = _mapper.Map<IEnumerable<ProductViewModel>>(product);
            return View(mapModel);

        }

        public async Task<IActionResult> AddPhoto(int id)
        {
            var product = await _context.productUW.GetByIdAsync(id);
            ViewBag.ProductId = id;
            ViewBag.Photo = product.ProductImage;
            ViewBag.Alt = product.Alt;
            ViewBag.title = product.Title;

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddPhoto(IFormFile file, ProductGalleryViewModel gallery)
        {
            if (!ModelState.IsValid)
                return View(gallery);

            if (file != null)
            {
                string imgname = "Img/Product/" + UploadFiles.CreateImg(file, "Product");
                if (imgname == "false")
                {
                    return View(gallery);
                }
                var photo = new ProductGallery
                {
                    ImageUrl = imgname,
                    ProductId = gallery.ProductId,
                    Alt = gallery.Alt,
                    Title = gallery.Title,
                };

                await _context.galleryUW.Create(photo);
                await _context.saveAsync();
                _notify.Success("You add a photo for product Gallery  !", 5);
                return RedirectToAction(nameof(AddPhoto));
            }
            return View(gallery);
        }


        public async Task<IActionResult> Delete(int id, string url, int productId)
        {
            var pic = await _context.galleryUW.GetByIdAsync(id);
            UploadFiles.DeleteImg("Product", pic.ImageUrl);
            await _context.galleryUW.DeleteByIdAsync(id);
            await _context.saveAsync();
            ViewBag.ProductId = productId;
            ViewBag.Photo = url;
            _notify.Error("You deleted a photo from product Gallery  !", 5);
            return RedirectToAction(nameof(Index));
        }


    }
}

Final_Wave/Areas/AdminArea/Views/ProductGallery/AddPhoto.cshtml
@model ProductGalleryViewModel
@{
    ViewData["Title"] = "AddPhoto";
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="container mt-4">
                <div class="row">
                    <div class="alert alert-light alertstyle mb-3">
                        <i class="fa fa-picture-o "> Product Gallery</i>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="mb-1 mt-3 col-4 offset-4 ">
                           <div class="card">
                                  <img src="~/@ViewBag.Photo"  alt="@ViewBag.Alt" title="@ViewBag.title" height="180" />
                           </div>
                    </div>
                    <div class="mb-1 mt-3 col-8  offset-2 card-box">
                           
                            <form asp-controller="ProductGallery" asp-action="AddPhoto" method="post" class="mt-5" enctype="multipart/form-data">   
                                <input asp-for="ProductId" type="hidden"  value="@ViewBag.ProductId" />
                                    <div class="ml-3 mb-3 mr-3 ">
                                       <label> ImageGallery</label>
                                        <input type="file" name="file" class="form-control "  autocomplete="off" class="form-control" />
                                       <span asp-validation-for="ImageUrl" class="text-danger"></span>
                                    </div>

                                     <div class="ml-3 mb-3 mr-3 ">
                                       <label> ImageAlt</label>
                                        <input type="text"  asp-for="Alt" class="form-control "  placeholder="alt" autocomplete="off" class="form-control" />
                                       <span asp-validation-for="Alt" class="text-danger"></span>
                                    </div>

                                     <div class="ml-3 mb-3 mr-3 ">
                                       <label> ImageTitle</label>
                                        <input type="text"  asp-for="Title" class="form-control "  placeholder="title" autocomplete="off" class="form-control" />
                                       <span asp-validation-for="Title" class="text-danger"></span>
                                    </div>
                               
                                   <div class="form-group text-right m-b-0 d-flex justify-content-center">
                                       <div class="mr-3 mb-3">
                                          <button class="btn btn-success btn-colorsave " type="submit">
                                               Save  <i class="fa fa-plus"></i>
                                          </button>
                                        </div>&nbsp;
                                       <div class="ml-3 mb-3">
                                         <a asp-action="Index" class="btn btn-back btn-primary">
                                              mainpage
                                         </a>
                                       </div>
                                   </div>
                            </form>
                    </div>
                </div>
             </div>

        </div>
    </div>
     <div class="row mt-5">
         @(await Component.InvokeAsync("GalleryComponent", @ViewBag.ProductId))
    </div>
</div>

Final_Wave/Areas/AdminArea/Views/ProductGallery/Index.cshtml
@model IEnumerable<ProductViewModel>
@{
    ViewData["Title"] = "ShowProduct";
    var counter = 1;
}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="container mt-4">
                <div class="row">
                    <div class="alert alert-light alertstyle mb-3">
                       <i class="fa  fa-picture-o "> Gallery</i>
                    </div> 
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="mb-2 mt-3">
                 
                          <i class="fa fa-search fabg  ">
                             <input type="text" id="myInput" onkeyup="myfunction()" placeholder="search Product..." class="search" />
                         </i>
                    </div>
                 <div class="table-responsive table-style">
                    <table class="table table-bordered table-hover table-striped mt-4   " id="myTable">
                        <thead class="bgcolor   ">
                            <tr class="text-center">
                                  <th scope="col">#</th>
                                <th scope="col">ProductName</th>
                                 <th scope="col">ProductImage</th>
                                <th scope="col">IsActive</th>
                                 <th scope="col">Category</th>
                                 <th scope="col">Operation</th>
                            </tr>
                        </thead>
                        <tbody>
                              @foreach (var item in Model)
                                {
                                     <tr>
                                          <td scope="row">@counter</td>
                                          <td>@item.ProductName</td>
                                          <td>
                                             <img src="~/@item.ProductImage" alt="@item.Alt" title="@item.Title" class="imgsize img-thumbnail"/>
                                          </td>
                                         <td style="color:@(item.IsActive? "green": "darkred"); font-weight:bold; ">@(item.IsActive? "Active" : "InActive")</td>
                                        <td>@item.CategoryId</td>
                                         <td>
                                              <a class="btn customBlue" asp-controller="ProductGallery" asp-action="AddPhoto" title="photo" asp-route-id="@item.Id">
                                                <i class="fa fa-picture"> Add photo</i>
                                             </a>
                                         </td>
                                     </tr>
                                 counter++;
                                }
                            </tbody>
                    </table>
                  </div>
                </div>
             </div>

          </div>
     </div>
 </div>
@section AdminScripts
    {
    <script>
        function myfunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            for (var i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];

                if (td) {
                    txtValue = td.textContent || td.innerText;

                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
    }