Final_Wave/Areas/AdminArea/Controllers/NotationController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Final_Wave.Core.ViewModels;
using Final_Wave.DataLayer.Entites;
using Final_Wave.DataLayer.Migrations;
using Final_Wave.DataLayer.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using static Final_Wave.Core.ViewModels.NotationViewModel;

namespace Final_Wave.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize]
    public class NotationController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;
        private readonly INotyfService _notify;
        public NotationController(INotyfService NOTY ,IUnitOfWork unit, UserManager<ApplicationUser> user,IMapper mapper)
        {
            _context = unit;
            _userManager = user;
            _mapper = mapper;
            _notify = NOTY;
        }
        public async Task<IActionResult> Index()
        {
            var notations = await _context.NotationUW.GetEntitiesAsync(x => x.UserID_Creator == _userManager.GetUserId(HttpContext.User), null, "User_Creator");
            return View(notations);
        }

        public async Task<IActionResult> GetNotation(int orderId)
        {
            var order = await _context.orderUW.GetByIdAsync(orderId);
            ViewBag.orderId = order.Id;
            ViewBag.reciever = order.UserId;
            return View(); ;
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetNotation(NotationSentViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);


            Notation notation = new Notation
            {
                NotationContent = model.NotationContent,
                NotationTitle = model.NotationTitle,
                NotationDate = DateTime.Now,
               UserID_Creator = _userManager.GetUserId(HttpContext.User),
               UserID_Reciever = model.UserID_Reciever
            };
            await _context.NotationUW.Create(notation);
            await _context.saveAsync();

            _notify.Success("You successfuly Sent  !", 5);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Index(SentNotationListViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            ViewBag.userId_Reciever = new SelectList(await _context.UserUW.GetEntitiesAsync(), "Id", "FullName", "usrimag ");
            model.UserID_Creator = _userManager.GetUserId(HttpContext.User);
            model.NotationDate = DateTime.Now;
            var mapModel = _mapper.Map<Notation>(model);
            await _context.NotationUW.Create(mapModel);
            await _context.saveAsync();
            _notify.Success("You successfully orderd!", 5);
            return RedirectToAction(nameof(Index)); ;


        }


        public async Task<IActionResult> Read(int id)
        {
            var notation = await _context.NotationUW.GetByIdAsync(id);
            notation.IsAccept = true; 
            _notify.Information("You checked all the notation !", 5);
            return View(notation);
        }
    }
}

Final_Wave/Areas/UserArea/Controllers/NotationController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Final_Wave.DataLayer.Entites;
using Final_Wave.DataLayer.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Final_Wave.Areas.UserArea.Controllers
{
    [Area("UserArea")]
    [Authorize]
    public class NotationController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;
        private readonly INotyfService _notify;
        public NotationController(INotyfService NOTY, IUnitOfWork unit, UserManager<ApplicationUser> user, IMapper mapper)
        {
            _context = unit;
            _userManager = user;
            _mapper = mapper;
            _notify = NOTY;
        }
        public async Task<IActionResult> Index()
        {
            var notations = await _context.NotationUW.GetEntitiesAsync(x => x.UserID_Reciever == _userManager.GetUserId(HttpContext.User), null, "User_Creator");
            return View(notations);
        }

        public async Task<IActionResult> Accept(int notationId)
        {
            var notaton = await _context.NotationUW.GetByIdAsync(notationId);
            notaton.IsAccept = true;
             _context.NotationUW.Update(notaton);
            await _context.saveAsync();
            _notify.Information("You accepted  the notation form !", 5);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Read(int id)
        {
            var notation = await _context.NotationUW.GetByIdAsync(id);
            _notify.Information("You checked all the notation !", 5);
            return View(notation);
        }
    }
}

Final_Wave/Areas/AdminArea/Views/Notation/GetNotation.cshtml
@using static Final_Wave.Core.ViewModels.NotationViewModel
@model NotationSentViewModel

@{
    ViewData["Title"] = "Notification";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="container mt-4">
                <div class="row">
                    <div class="alert alert-light alertstyle mb-3">
                        <i class="fa fa-user ">  add Notation </i>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="mb-1 mt-3 col-10 offset-1 card-box">
                        <form asp-controller="Notation" asp-action="GetNotation" method="post" class="mt-5" autocomplete="off">

                            <div class="ml-3 mb-3 mr-3 ">
                                    <label>Title</label>
                                    <input type="text" asp-for="NotationTitle" class="form-control " placeholder=" title ..." autocomplete="off" class="form-control" />
                                    <span asp-validation-for="NotationTitle" class="text-danger"></span>
                               </div>

                               

                               <div class="ml-3 mb-3 mr-3">
                                    <label>Description</label>
                                    <textarea type="text" asp-for="NotationContent" class="form-control " placeholder=" Description..." autocomplete="off" ></textarea>
                                    <span asp-validation-for="NotationContent" class="text-danger"></span>
                               </div>

                               <input asp-for="UserID_Reciever" value="@ViewBag.reciever" hidden />

                               <div class="form-group text-right m-b-0 d-flex justify-content-center">
                                  <div class="mr-3 mb-3">
                                      <button class="btn btn-success btn-colorsave " type="submit">
                                         Send  <i class="fa fa-plus"></i>
                                      </button>
                                  </div>&nbsp;
                                   <div class="ml-3 mb-3">
                                        <a asp-action="Index" class="btn btn-back btn-primary">
                                         Cancel
                                        </a>
                                   </div>
                                </div>
                            </form>
                    </div>
                </div>
             </div>

        </div>
    </div>
</div>
<script src="~/panel/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace("NotationContent");
</script>

Final_Wave/Areas/AdminArea/Views/Notation/Index.cshtml
@model IEnumerable<Notation>
@{
    ViewData["Title"] = "Index";
    var counter = 1;
}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="container mt-4">
                <div class="row">
                    <div class="alert alert-light alertstyle mb-3">
                        <i class="fa fa-plus "> Order</i>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="mb-2 mt-3 wrapper">
                    <i class="fa fa-search fabg ">
                        <input type="text" id="myInput" onkeyup="myfunction()" placeholder="search ..." class="search" />
                    </i>
                </div>
                <div class="row">
                    <div class="table-responsive table-style">
                        <table class="table table-bordered table-hover table-striped mt-4   " id="myTable">
                            <thead class="bgcolor   ">
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Sender</th>
                                    <th scope="col">Recieved Date</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Operation</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="text-center">@counter</td>
                                        <td class="text-center">@item.User_Creator.FullName</td>
                                        <td class="text-center">@item.NotationDate.ToString("dddd, dd MMMM yyyy")</td>
                                        <td class="text-center">@item.NotationTitle</td>

                                        <td class="text-center">
                                            <a asp-action="Read" asp-route-id="@item.NotationID" title="Read" asp-controller="Notation" class="btn-success btn mr-3 mb-1 "><i class="fa fa-book "></i></a>
                                            @if (item.IsAccept)
                                            {
                                                <span class="btn btn-info">Accepted</span>   
                                            }
                                            else
                                            {
                                                <span class="btn btn-warning">Rejected</span>
                                            }
                                        </td>

                                    </tr>
                                    counter++;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@section AdminScripts
    {
    <script>
        function myfunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (var i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
    }

Final_Wave/Areas/AdminArea/Views/Notation/Read.cshtml
@model Notation
@{
    ViewData["Title"] = "Detials";
}


<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="container mt-1">
                <div class="row">
                    <div class="alert alert-info alertstyle mb-3">
                        <i class="fa fa-book"> Notation Details</i>
                    </div>
                </div>
            </div>
            <div class="col-8 mt-5  offset-2">
                <div class="container mt-5">
                    <div class="divstyle-detail">
                        <div class="row p-5">
                            <div class="col-12">
                                <p> <strong>NotationDate : </strong>@Model.NotationDate </p>
                                <p> <strong>NotationId : </strong>@Model.NotationID </p>
                                <p> <strong>User_sender : </strong>@Model.UserID_Creator </p>
                                <p><strong>Short_Description : </strong>@Html.Raw(Model.NotationContent)</p>
                                <p> <strong>Isaccpet : </strong> @Model.IsAccept</p>
                                <p> <strong>Title : </strong> @Model.NotationTitle</p>

                            </div>
                        </div>
                        <div class="form-group text-right m-b-0 d-flex justify-content-center">
                            <a asp-action="Index" class="btn btn-back mb-3"> Dack</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>